#!/usr/bin/env bash

function fix() {
  case "$1" in

    # `fix audio` | When audio isn't working
    "audio") sudo pkill coreaudiod ;;

    # `fix app /Applications/name.app` | When an app tells you "This app is damaged and can't be opened. You should move it to the trash."
    "app") xattr -rc ;;

    # `fix launchservices` - Remove LaunchServices duplicates in the "Open With" menu
    "launchservices") /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder ;;

  esac
}

complete -W "audio app launchservices" fix

function remove() {
  case "$1" in

    # `remove cache` | Clear cache
    "cache")
        rm -rf .cache
        rm -rf .composer/cache
        rm -rf .expo/*cache
        rm -rf .gradle/caches
        rm -rf ~/Library/Application\ Support/Keybase/kbfs_block_cache
        rm -rf ~/Library/Application\ Support/Google/DriveFS/cef_cache/Cache
        rm -rf ~/Library/Developer/CoreSimulator
    ;;

    # `remove clipboard` | Clear clipboard
    "clipboard") pbcopy < /dev/null ;;

    # `remove logs`
    # Clear Apple's System Logs to improve shell startup speed.
    # Clear download history from quarantine.
    "logs") sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent' ;;

    # `remove ds_store` | Recursively delete `.DS_Store` files
    "ds_store") find . -type f -name '.DS_Store' -ls -delete; killall Finder ;;

    # `remove launchpad_icon name` | Remove stuck icon from launchpad. Sometimes after youd elete an app, it is still in Launchpad.
    "launchpad_icon")
      sqlite3 $(find /private/var/folders \( -name com.apple.dock.launchpad -a -user $USER \) 2> /dev/null)/db/db "DELETE FROM apps WHERE title='$2';" && killall Dock
    ;;

    # `remove trash` | Empty the Trash on all mounted volumes and the main HDD.
    "trash") sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash ;;

  esac
}

complete -W "cache clipboard logs ds_store launchpad_icon trash" remove
