#!/usr/bin/env bash

function update() {
  case "$1" in

    # `update brew`
    "brew")
      brew upgrade; brew missing; brew cleanup; brew services cleanup
      cd ~//packages/
      brew bundle dump --force --describe
      cd -
    ;;

    # `update dotfiles`
    "dotfiles") ~//dotfiles/install.sh ;;

    # `update hosts`
    "hosts") sudo chmod -R o+rwx /etc/hosts; cp ~//resources/hosts /etc/hosts ;;

    # `update repos` | In current directory
    "repos") for d in *; do pushd $d && git pull && popd; done ;;

    # `update symlinks`
    "symlinks")
      #==============================================================================#
      # Google Drive Symlinks :: from Mycroft to Google Drive
      #==============================================================================#
      gd="/Volumes/GoogleDrive/My Drive"
      if [ -d "$gd" ]; then
        cd "$gd"
        for src in Documents Documents/Repos/gsc Documents/Notes/Legal Documents/Projects Documents/Projects/YouTube Games Music Pictures; do
          cd "$gd/$src"
          for dir in ./; do
            run=(
              stow --target ~/$src    # target directory
                   --restow           # prunes dead links
                   --verbose 1 "$dir" # options 0-5
                   # --simulate       # use for testing
            )
            "${run[@]}"
          done
        done
      fi

      #==============================================================================#
      # Adler Symlinks :: from Mycroft to Adler
      #==============================================================================#
      adler="/Volumes/Adler"
      if [ -d "$adler" ]; then
        cd "$adler"
        for src in Documents/Computer Games Pictures; do
          cd "$adler/$src"
          for dir in ./; do
            run=(
              stow --target ~/$src    # target directory
                   --restow           # prunes dead links
                   --verbose 1 "$dir" # options 0-5
                   # --simulate       # use for testing
            )
            "${run[@]}"
          done
        done
      fi

      #==============================================================================#
      # Other Symlinks
      #==============================================================================#
      ln -s /Applications/ ~/Applications/Mac
    ;;

    # `update` | Get macOS Software Updates, update packages, and general cleanup
    # TODO: implement this? https://github.com/fwartner/mac-cleanup/blob/master/cleanup.sh
    "")
      echo
      echo ':update'
      echo
      sama
      cd ~
      echo
      echo 'Symlinks'
      echo '················································································'
      echo
      echo 'Updating symlinks…'
      update symlinks
      echo
      echo 'Dotfiles'
      echo '················································································'
      echo
      echo 'Updating dotfiles…'
      update dotfiles
      echo
      echo 'MAS'
      echo '················································································'
      echo
      echo 'Updating mas apps…'
      mas upgrade
      echo
      echo 'Homebrew'
      echo '················································································'
      echo
      echo 'Updating brew packages…'
      update brew
      echo
      echo 'NPM'
      echo '················································································'
      echo
      echo 'Updating npm modules…'
      npm update -g; npm cache clean --force
      echo
      echo 'PIP'
      echo '················································································'
      echo
      echo 'Updating python packages…'
      pip3 install --upgrade pip
      pip3 install -U $(pip freeze | cut -d '=' -f 1)
      echo
      echo 'Hosts'
      echo '················································································'
      echo
      echo 'Updating hosts…'
      update hosts
      echo
      echo 'Git Repositories'
      echo '················································································'
      echo
      echo 'Updating git repos…'
      cd ~/Documents/Repos/
      update repos
      cd ~
      echo
      echo 'Sublime Text'
      echo '················································································'
      echo
      echo 'Backing up Sublime Text settings…'
      cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Package\ Control.sublime-settings ~//resources/
      cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings ~//resources/
      echo
      echo 'macOS'
      echo '················································································'
      echo
      echo 'Running macOS update…'
      softwareupdate -i -a
      echo
      echo 'Cleaning'
      echo '················································································'
      echo
      echo 'Deduping ssh known hosts…'
      cat ~//dotfiles/.ssh/known_hosts | uniq > ~//dotfiles/.ssh/known_hosts2; mv ~//dotfiles/.ssh/known_hosts2 ~//dotfiles/.ssh/known_hosts # add "| sort" to list in abc order
      echo 'Clear cache…'
      rm -rf .cache
      rm -rf .composer/cache
      rm -rf .expo/*cache
      rm -rf .gradle/caches
      rm -rf ~/Library/Application\ Support/Keybase/kbfs_block_cache
      rm -rf ~/Library/Application\ Support/Google/DriveFS/cef_cache/Cache
      rm -rf ~/Library/Developer/CoreSimulator
      sudo rm -rf /Applications/Google\ Docs.app
      sudo rm -rf /Applications/Google\ Sheets.app
      sudo rm -rf /Applications/Google\ Slides.app
      echo 'Clear clipboard…'
      pbcopy < /dev/null
      echo 'Clear logs…'
      sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
      echo 'Empty trash…'
      sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash
      echo
      echo 'Setting Preferences…'
      ~//preferences
      ~//dock
      echo
      echo 'COMPLETE'
    ;;

  esac
}

complete -W "brew dotfiles hosts repos symlinks" update
